name: Game Space
favicon: null
layout_spectrum: 0.06448459927923977
typography_spectrum: 0.4115939966868609
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.012577215442433953
  lightness: 0.8656239323318005
  saturation: 0.4018371575511992
  rhythmicContrast: 0.7886950606480241
purpose: []
